#!/usr/bin/env python3
"""Write a gameplay playtest for tools/smstest that needs no harness data:
boot -> intro -> title -> every selectable level, played with the pad, with
the inventory opened and closed through PAUSE.  Conrad's fields are read at
fixed offsets into pge_live (pge.h), so the script is generated from the
ROM's own symbol file.   Usage: mkgameplay.py flashback.noi > script.txt"""
import sys

noi = {}
for line in open(sys.argv[1]):
    p = line.split()
    if len(p) == 3 and p[0] == 'DEF':
        noi[p[1].lstrip('_')] = int(p[2], 16)
pge = noi['pge_live']
X, Y, ROOM = hex(pge + 2), hex(pge + 4), hex(pge + 15)     # LivePGE offsets
inventory = 'inv_open' in noi and 'ST_INVENTORY'          # main and the merge
out = []
w = out.append
w(f"symbols {sys.argv[1]}")
w("echo boot: the intro starts and a press skips it to the title")
w("run 600")
w("expect game_state == 0 w1")
w("expectvdp display 1")
w("expectcolors 4")
w("screenshot shots/gp/intro.ppm")
w("tap 1")
w("waituntil game_state == 1 900 w1")
w("run 30")
w("expectvdp display 1")
w("expectcolors 4")
w("screenshot shots/gp/title.ppm")
w("echo PAUSE on the title does nothing")
w("pause")
w("run 10")
w("expect game_state == 1 w1")

def play_level(sel):
    w(f"echo ---- level choice {sel} ----")
    w("expect game_state == 1 w1")
    w(f"expect level_sel == {sel} w1")
    w("tap 1")
    w("run 20")
    w("echo the level's intro, if it has one, is skipped with a press")
    w("tap 2")
    w("waituntil game_state == 2 1200 w1")
    w("expect logic_running == 1 w1")
    w("run 120")
    w("expectvdp display 1")
    w("expectcolors 6")
    w(f"screenshot shots/gp/l{sel}_start.ppm")
    w("print logic_frame")
    w("print logic_cur_room w1")
    w(f"print {X}")
    w("print sfx_started")
    w("echo walk right, then left, then run and jump")
    w("hold right")
    w("run 150")
    w(f"print {X}")
    w(f"print {ROOM} w1")
    w("hold left")
    w("run 150")
    w(f"print {X}")
    w("hold left+1")
    w("run 90")
    w("hold up")
    w("run 40")
    w("hold right+up")
    w("run 60")
    w("hold down")
    w("run 40")
    w("hold none")
    w("run 60")
    w(f"screenshot shots/gp/l{sel}_played.ppm")
    w("expect game_state == 2 w1")
    w("expect logic_bad_op == 0 w1")
    w("expect logic_running == 1 w1")
    w("expect watchdog < 10 w1")
    w("print logic_frame")
    w("print sim_sprites w1")
    w("print ticks_behind")
    w("print sfx_started")
    w(f"print {X}")
    w(f"print {Y}")
    w(f"print {ROOM} w1")
    if inventory:
        w("echo PAUSE opens the inventory; PAUSE again closes it")
        w("pause")
        w("run 20")
        w("expect game_state == 3 w1")
        w("expectvdp display 1")
        w(f"screenshot shots/gp/l{sel}_inventory.ppm")
        w("pause")
        w("run 20")
        w("expect game_state == 2 w1")
        w("run 60")
        w("expectvdp display 1")
        w("expectcolors 6")
        w("echo button 1 also closes it, and play carries on")
        w("pause")
        w("run 20")
        w("expect game_state == 3 w1")
        w("tap 1")
        w("run 20")
        w("expect game_state == 2 w1")
        w("hold right")
        w("run 60")
        w("hold none")
        w("run 30")
        w("expect logic_bad_op == 0 w1")
        w("echo both buttons in the inventory quit to the title")
        w("pause")
        w("run 20")
        w("expect game_state == 3 w1")
        w("hold 1+2")
        w("run 4")
        w("hold none")
    else:
        w("echo PAUSE leaves the level")
        w("pause")
    w("waituntil game_state == 1 300 w1")
    w("run 40")

for sel in range(5):
    if sel:
        w("echo pick the next level on the title")
        w("tap down")
        w("run 10")
    play_level(sel)
print('\n'.join(out))
